apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    system: nginx
  name: test-ds
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      system: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        system: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}

