apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-1
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: job-container
        image: busybox
        command: ["/bin/sleep", "15"]
      terminationGracePeriodSeconds: 0
