apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-2
spec:
  completions: 3
#  parallelism: 2
#  activeDeadlineSeconds: 30
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: job-container
        image: busybox
        command: ["/bin/sleep", "15"]
      terminationGracePeriodSeconds: 0
