apiVersion: v1
kind: Pod
metadata:
 name: pod-2
spec:
 affinity:
  nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:   
    nodeSelectorTerms:
    - matchExpressions:
      -  {key: team2, operator: Exists}
 containers:
 - name: container
   image: nginx
 terminationGracePeriodSeconds: 0

