apiVersion: v1
kind: Pod
metadata:
 name: pod-prefer
spec:
 affinity:
  nodeAffinity:
   preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
       matchExpressions:
       - {key: prod, operator: Exists}
 containers:
 - name: container
   image: nginx
 terminationGracePeriodSeconds: 0

