apiVersion: v1
kind: Pod
metadata:
 name: pod-affinity
spec:
 affinity:
  podAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:   
   - topologyKey: team
     labelSelector:
      matchExpressions:
      -  {key: type, operator: In, values: [db2]}
 containers:
 - name: container
   image: nginx
 terminationGracePeriodSeconds: 0

