apiVersion: v1
kind: Pod
metadata:
  name: primary
  labels:
     role: primary
spec:
  nodeSelector:
    team: prod
  containers:
  - name: container
    image: nginx
  terminationGracePeriodSeconds: 0

