apiVersion: v1
kind: Pod
metadata:
  name: pod-live-2
  labels:
    app: liveness
spec:
  containers:
  - name: test-liveness
    image: dhdockerhu/test:html2
    ports:
    - containerPort: 80
    livenessProbe:
      exec:
        command: ["ls", "/usr/share/nginx/html/health"]
      initialDelaySeconds: 5
      periodSeconds: 3
      failureThreshold: 3
    volumeMounts:
    - name: hostpath
      mountPath: /usr/share/nginx/html
  volumes:
  - name : hostpath
    hostPath:
      path: /app

