apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /share
    server: master1   #<-- Edit to match master node
    readOnly: false

